version: '3'
services:
  minthack-backend:
    build:
      context: ./backend
    ports:
      - "3080:3080"
    container_name: minthack-backend
    volumes:
       - ./backend:/usr/src/app/backend
       - /usr/src/app/backend/node_modules
  minthack-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: minthack-frontend
    stdin_open: true
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules